### ISSUE TITLE
Example Error

### ISSUE THREAD

**Issue by gsquire** [alexcrichton/futures-timer#7]
For some reason, I cannot compile the `Interval` example:

```sh
   Compiling timer v0.1.0 (file:///Users/gsquire/scratch/timer)
error[E0599]: no method named `take` found for type `futures_timer::Interval` in the current scope
  --> src/main.rs:11:10
   |
11 |         .take(4)
   |          ^^^^
   |
   = note: the method `take` exists but the following trait bounds were not satisfied:
           `futures_timer::Interval : futures::StreamExt`
           `&futures_timer::Interval : futures::StreamExt`
           `&mut futures_timer::Interval : futures::StreamExt`
           `&mut futures_timer::Interval : std::iter::Iterator`
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
4  | use futures::stream::Stream;
   |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `timer`.

To learn more, run the command again with --verbose.
```

I have `futures = "0.2"` in my Cargo.toml and know that the prelude includes the `Stream` trait. Am I missing something totally obvious?

**Comment by gsquire** [comment]
I was able to get the example working with `futures = "0.1"`:

```rust
extern crate futures;
extern crate futures_timer;

use std::time::Duration;

use futures::prelude::*;
use futures_timer::Interval;

fn main() {
    Interval::new(Duration::from_secs(1))
        .take(4)
        .for_each(|()| Ok(println!("tick...")))
        .wait()
        .unwrap();
}
```

**Comment by alexcrichton** [comment]
Ah yes unfortunately this library isn't compatible with 0.2 yet, it's still using 0.1

**Comment by gsquire** [comment]
No problem, sounds like a new version just hasn't been release yet? I'll close this out. Thanks.
